name: End-to-End Tests
on: push
jobs:
  cypress-run:
    runs-on: ubunto-22.04
    steps:
      - namee: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
